import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { REPO_ROOT, SOLVER_ENV_PATH } from "./solver-env.mjs";

const VERSION = "v0.2.0";
const ASSET = "TexasSolver-v0.2.0-MacOs.zip";
const URL = `https://github.com/bupticybee/TexasSolver/releases/download/${VERSION}/${ASSET}`;
const INSTALL_ROOT = path.join(REPO_ROOT, ".solver-bin");
const ZIP_PATH = path.join(INSTALL_ROOT, ASSET);
const SOLVER_DIR = path.join(INSTALL_ROOT, "TexasSolver-v0.2.0-MacOs");
const SOLVER_BIN = path.join(SOLVER_DIR, "console_solver");

function run(cmd, args, opts = {}) {
  const res = spawnSync(cmd, args, { stdio: "inherit", ...opts });
  if (res.status !== 0) process.exit(res.status || 1);
}

function writeEnv() {
  const text = [
    "# Auto-generated by npm run solver:install.",
    "# This file is ignored by git because these paths are machine-local.",
    `TENGAN_SOLVER_BIN=${SOLVER_BIN}`,
    `TENGAN_SOLVER_CWD=${SOLVER_DIR}`,
    "# TENGAN_SOLVER_PORT=7333",
    ""
  ].join("\n");
  fs.writeFileSync(SOLVER_ENV_PATH, text);
}

if (process.platform !== "darwin") {
  console.error("solver:install currently installs the official macOS TexasSolver release only.");
  console.error("For other platforms, download TexasSolver manually and edit .solver.env.");
  process.exit(1);
}

fs.mkdirSync(INSTALL_ROOT, { recursive: true });

console.log(`Downloading official TexasSolver ${VERSION} macOS release...`);
run("curl", ["-L", "-o", ZIP_PATH, URL], { cwd: REPO_ROOT });

console.log("Extracting TexasSolver...");
run("unzip", ["-q", "-o", ZIP_PATH, "-d", INSTALL_ROOT], { cwd: REPO_ROOT });

if (!fs.existsSync(SOLVER_BIN)) {
  console.error(`Expected solver binary not found: ${SOLVER_BIN}`);
  process.exit(1);
}
fs.chmodSync(SOLVER_BIN, 0o755);
writeEnv();

console.log("");
console.log(`Installed real TexasSolver backend: ${SOLVER_BIN}`);
console.log(`Wrote config: ${SOLVER_ENV_PATH}`);
console.log("");
console.log("Next:");
console.log("  npm run solver");
